Adición de formatos para la extracción de datos
necronet/Prinzapolka pull request #24
Opened 2021-01-15 06:28 UTC by aaronjae22

### Format para el spider aurora. Testing purpose.
- Creación de **format.py** que contiene la manera en la que los datos son extraídos. **Source** se añadió en este archivo debido a que el spider correspondiente a property-nicararagua.com es llamado remax y si se hace el source mediante un `add_value('source', self.name)` el dato no es del todo correcto.
- Dentro de la carpeta correspondiente a aurora, se creó otro archivo llamado **format.py** que contiene los xpath y la manera en la que se tratan los items extraídos.
- En el spider de aurora, al extraer los datos se invoca a los métodos perteneciente a la clase AuroraFormat que se encuenta en el archivo **format.py** dentro de la carpeta **aurora**.

2021-01-15 06:33 UTC, necronet submitted a review, later dismissed
LGTM good work!

2021-01-16 03:49 UTC, necronet commented
lol it still failed @aaronjae22 

```ModuleNotFoundError: No module named 'geopy'```

2021-01-17 00:52 UTC, necronet commented
las pruebas estan fallando https://github.com/necronet/Prinzapolka/pull/24/checks?check_run_id=1715254834

2021-01-19 16:12 UTC, necronet commented
Keeps failing 

```Traceback (most recent call last):
  File "/home/runner/work/Prinzapolka/Prinzapolka/bienesraices/tests/aurora_spider_test.py", line 23, in test_get_item_success
    self.assertIsNotNone(item['email'])
  File "/opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/site-packages/scrapy/item.py", line 93, in __getitem__
    return self._values[key]
KeyError: 'email'
```

2021-01-20 06:22 UTC, necronet approved these changes
LGTM

2021-01-23 15:41 UTC, aaronjae22 commented
- En el commit de hoy (23-01) se agregó un nuevo archivo llamado **expected_values.py**, el cual contiene todos los expected values de los tests.
- Los **response.html** de todos los sitios se cambiaron para seleccionar url especificas que contienen todos o la mayoría de datos que se extraen y así generar tests más completos.
- Se realizaron modificaciones a la manera en la que los datos son tratados al ser extraídos ya que en algunas ocasiones, ciertos elementos causaban conflictos con la nueva estructura de los tests.
En este caso, se eliminó de **base_item.py** los métodos MapCompose**(**remove_tags, etc**)** y Join**()** en los campos img, location y contact. Esto se sustituyó con un método en **format.py** llamado **def not_found()**.

2021-01-23 15:51 UTC, aaronjae22 commented
- En el archivo **expected_values.py** hay un warning sobre el uso de **self** en los métodos y en su llamado. Al agregarlo cómo parámetro en expected_values.py y luego en el llamado genera un conflicto. Se optó por no colocarlo en la declaración ni en llamado. Informarme sobre esto.
- Comando para invocar un solo test: `python -m unittest tests.nombre_spider_test`.


**PENDIENTE**
En el método `**def checkExpectedValues(self, item):**` se están verificando únicamente los keys de los values. Se debe ingresar a cada uno de los elementos de los demás diccionarios (contact, imgs, location).

2021-01-24 05:12 UTC, necronet commented on requirements.txt
> +Django==3.1.5
Probablemente debeiras de quitar django de las dependencias no creo que lo ocupamos aca

2021-01-24 05:13 UTC, necronet commented on requirements.txt
> +pytz==2020.5
para que usas pytz ?

2021-01-24 05:13 UTC, necronet commented on requirements.txt
> +sqlparse==0.4.1
Busque donde usamos `sqlparse` pero no encontre referencia

2021-01-24 05:14 UTC, necronet requested changes
Only some minor changes in regards to `requirements.txt`

2021-01-26 22:36 UTC, necronet approved these changes
LGTM great changes

2021-01-27 04:04 UTC, merged