Format
necronet/Prinzapolka pull request #29
Opened 2021-02-13 22:32 UTC by aaronjae22

- Changes made to **Aurora** regarding to the way the prices are being extracted.
- Contact images as well as the features of every site are now part of the items.

2021-02-13 22:48 UTC, necronet commented on bienesraices/bienesraices/spiders/Aurora/format.py
>  class AuroraFormat(SpiderFormat):
Formatter parece estar teniendo un sin numero de responsabilidades, esto puede ser problematico puesto que no tiene una unica responsabilidad, muy probablemente migremos parte del comportamiento de estas clases mas a Item Pipelines, por ejemplo mandariamos un dirty Item que contenga los features:

{ rawFeatures: "F1, f2, F3, F4 ,F5" } ==send to pipeline==> |Item Feature Pipeline| === output ===> | {features :["f1","f2","f3"]}

Por el momento lo podemos dejar aca, solo es para tenerlo en consideraccion.

2021-02-13 22:50 UTC, necronet commented on bienesraices/bienesraices/spiders/Aurora/format.py
> +        if numbers != 'Not Found':
Por que un numbers estaria como 'Not found' ?

2021-02-13 22:56 UTC, necronet requested changes

2021-02-13 22:56 UTC, necronet commented on bienesraices/bienesraices/spiders/Aurora/spider.py
> +        loader.add_value('contact', formatter.contactFormat(response))
No deberia ser necesario enviarle response como parametro ya, por que lo envias si los formatter ya contienen un `self.response`?

2021-02-13 22:56 UTC, necronet commented on bienesraices/bienesraices/spiders/Aurora/format.py
> +    def contactFormat(self,response):
No es necesario el parametro response, en vez usar `self.response`

2021-02-13 22:56 UTC, necronet commented on bienesraices/bienesraices/spiders/Casas24/spider.py
> +            loader.add_value('location',formatter.location(local))'''
esto esta causando que las pruebas fallen para location

2021-02-13 22:56 UTC, necronet commented on bienesraices/bienesraices/spiders/Heaven/format.py
>          contact["name"] = "7thheavenproperties"
Quizas va siendo momento que utilizemos objetos de python en vez de usar diccionarios!

2021-02-13 22:56 UTC, necronet commented on bienesraices/bienesraices/spiders/Momotombo/format.py
> +        phones_list = self.not_found(str(self.response.xpath('substring-after((//div[@class="col-sm-4"]//span)[2],"Teléfonos:  ")').extract_first()))
En vez de `"Teléfonos:   "` esto puede ser algun regex asi? `[A-zÀ-ú]+\:\s+`

2021-02-15 05:12 UTC, necronet commented
Todavia no has resuelto el resto de comentarios o con respuestas para antes de confirmarlo

2021-02-15 15:54 UTC, aaronjae22 commented on bienesraices/bienesraices/spiders/Aurora/format.py
>  class AuroraFormat(SpiderFormat):
Dale. Me mantenes al tanto.

2021-02-15 16:13 UTC, aaronjae22 commented on bienesraices/bienesraices/spiders/Aurora/format.py
> +        if numbers != 'Not Found':
Siempre la condición será distinta que 'Not found' pero puse eso para poder llamar a la función en lugar de colocarla y llamarla en una sola línea de código. Ya lo reparo.

2021-02-15 16:13 UTC, aaronjae22 commented on bienesraices/bienesraices/spiders/Aurora/format.py
>  class AuroraFormat(SpiderFormat):
Dale. Me mantenes al tanto.

2021-02-15 16:41 UTC, aaronjae22 commented on bienesraices/bienesraices/spiders/Aurora/spider.py
> +        loader.add_value('contact', formatter.contactFormat(response))
Solucionado ya.

2021-02-15 16:42 UTC, aaronjae22 commented on bienesraices/bienesraices/spiders/Casas24/spider.py
> +            loader.add_value('location',formatter.location(local))'''
Solucionado ya. También tuve que cambiar los html debido a la adición de los features y las imagenes de los vendedores.

2021-02-15 16:43 UTC, aaronjae22 commented on bienesraices/bienesraices/spiders/Heaven/format.py
>          contact["name"] = "7thheavenproperties"
Dale. Voy a ir pensando en cómo modificarlos.

2021-02-15 17:18 UTC, aaronjae22 commented on bienesraices/bienesraices/spiders/Momotombo/format.py
> +        phones_list = self.not_found(str(self.response.xpath('substring-after((//div[@class="col-sm-4"]//span)[2],"Teléfonos:  ")').extract_first()))
Voy a trabajar en ello.

2021-02-15 23:31 UTC, necronet approved these changes
LGTM

2021-02-15 23:31 UTC, merged